#!/usr/bin/bash
#SBATCH --job-name=job
#SBATCH --partition=serc
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=2g
#SBATCH --time=20:00:00
#SBATCH --array=1-65

# Specify the path to the config file
config=/home/users/gkittles/DRIPP/config_curtailment_cost.txt

# Extract the sample name for the current $SLURM_ARRAY_TASK_ID
sample=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $2}' $config)

/home/groups/smfletch/miniconda3/envs/DRIPP/bin/python3 main.py $sample